name: Test

on:
  - push
  - pull_request

jobs:
  test-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Before Install
        run: |
          mkdir -p shogi/boards
          touch shogi/boards/temp.sqlite3

      - run: npm ci

      - name: Typecheck files not covered by tests
        run: npx tsc --noEmit
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Test
        run: npm run test:coverage
        env:
          NODE_OPTIONS: --trace-warnings --trace-deprecation --trace-exit --trace-uncaught --unhandled-rejections=strict --max-old-space-size=4096

      - name: Set up reviewdog
        if: ${{ github.event_name == 'pull_request' }}
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog
        continue-on-error: true
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git ls-files | grep eslintrc | xargs -L 1 dirname | paste -sd ' ' | xargs -I {} sh -c "npx eslint --ext js,ts -f rdjson {} | reviewdog -f=rdjson -name=ESLint -reporter=github-pr-review"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  test-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-23
          default: true
          override: true

      - name: build
        run: cargo build --all --verbose

      - name: test
        run: cargo test --all --verbose
